services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 443:443 # Port HTTPS
      - 80:80   # Port HTTP pour redirection
    volumes:
      # Montez les certificats Let's Encrypt dans le conteneur
      - /etc/letsencrypt/live/soundnation.duckdns.org:/etc/letsencrypt/live/soundnation.duckdns.org:ro
      - /etc/letsencrypt/archive/soundnation.duckdns.org:/etc/letsencrypt/archive/soundnation.duckdns.org:ro
      - /etc/letsencrypt/keys:/etc/letsencrypt/keys:ro
