version: '3'

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000  # Port interne du conteneur
    labels:
      - "traefik.enable=true"  # Activer le routage via Traefik
      - "traefik.http.routers.nodeapp.rule=Host(`soundnation.duckdns.org`)"  # Le domaine que tu utilises
      - "traefik.http.routers.nodeapp.entrypoints=websecure"  # Entrée HTTPS
      - "traefik.http.routers.nodeapp.tls.certresolver=myresolver"  # Utilisation de Let's Encrypt pour le SSL
      - "traefik.http.services.nodeapp.loadbalancer.server.port=3000"  # Port du conteneur sur lequel ton app Node écoute
    networks:
      - web

networks:
  web:
    driver: bridge
